title: AI for Good UK Events
about_content: |

  This is a calendar of events relating to "AI for Good" in and around the UK. We also have a new Discord community which you can access by clicking the icon below.

  ## Submit an event:
  To submit an event, click the "Add Event" button. Add  you event details and create a PR.
website_url: https://ai-for-good.events/
github_url: https://github.com/AndreasThinks/FastCalendar/edit/tech-for-good-events/events.yaml
default_locations:
  - Online
  - London
social_links:
  - name: Discord
    icon: discord-logo
    url: https://discord.gg/KUy8cB2t
  - name: RSS Feed
    icon: rss-simple
    url: /rss
