title: Tech for Good Events Calendar
about_content: |

  This is a calendar of events for the Tech for Good community in the UK.

  ## Submit an event:
  To submit an event, click the "Add Event" button. Add  you event details and create a PR.
website_url: https://tech-for-good.events/
github_url: https://github.com/AndreasThinks/FastCalendar/edit/tech-for-good-events/events.yaml
default_locations:
  - Online
  - London
social_links:
  - name: Discord
    icon: discord-logo
    url: hhttps://discord.gg/KUy8cB2t
  - name: RSS Feed
    icon: rss-simple
    url: /rss