[project]
name = "fastcalendar"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "feedgen>=1.0.0",
    "python-fasthtml>=0.6.4",
    "pyyaml>=6.0.2",
]
